### ISSUE TITLE
"reloading" scrolldepth

### ISSUE THREAD

**Issue by zepedrorocha** [robflaherty/jquery-scrolldepth#24]
Hello. I'm using AngularJS page routing (Multiple Views). Since i don't refresh the entire webpage your code will unbind scroll event, eventually.

```javascript
// If all marks already hit, unbind scroll event
      if (cache.length >= 4 + options.elements.length) {
        $window.off('scroll.scrollDepth');
        return;
      }
```

I wish I could "reload" the scrolldepth when the View is changed. I'm asking for some advise to find the best option. Thank you

**Comment by nandy-andy** [comment]
Hi!

I had similar issues. And I resolved them in [my fork](https://github.com/nandy-andy/jquery-scrolldepth/compare/robflaherty:master...master).

We're creating single page application with Ember and we wanted to use your useful plugin :smile_cat:  The issue was with caching in your plugin and detaching `scroll.scrollDepth` event after reaching all points. The changes I implemented are rather simple:
* I added a `detachEventOnceCacheIsFull` flag which is backward compatible but once set to `false` never detach the scroll event,
*  exposed a simple `reset()` method for resetting the cache while transitioning to new view.

@robflaherty, should I create a pull request and you'll merge it? Or do you want to wait till you remove jQuery dependency and you'll go with your version?

**Comment by robflaherty** [comment]
@nandy-andy Thanks, I think this is great. I'm wondering if there's a way to achieve the reset without requiring a new plugin option (I'm worried about the plugin becoming overloaded with options). What if the `reset` method detached and then reattached the scroll event handler?

A pull request would be awesome. A lot of people have asked for this feature so I'd like to go ahead and include it in the next version.

**Comment by robflaherty** [comment]
@nandy-andy Hey, if you want to submit a pull request for the work you already did, I can merge it into a dev branch and I'll work on modifying it so it doesn't require adding a new plugin option. If not, no worries :)

**Comment by nandy-andy** [comment]
Yeah, sorry. I wanted to play with it more but recently it's hard to find time. The pull request has been created: [PR#53](https://github.com/robflaherty/jquery-scrolldepth/pull/53)

**Comment by robflaherty** [comment]
@nandy-andy Thanks for the help. Hoping to release this and some other features sometime in the next few weeks.
