### ISSUE TITLE
> 25% non-interaction < 25% interaction

### ISSUE THREAD

**Issue by pkeesey** [robflaherty/jquery-scrolldepth#49]
I like the idea of non-interaction by default. However in some cases if someone get's to the bottom of screen it means they may have read the entire article etc. Is there a way I could implement this and have 25% be non-interaction but everything over 25% (or whatever we decide) is an interaction?

I am thinking about bounce rate.

**Comment by flinguin** [comment]
actually this is one of the main missing features imho - and as the issue is open for more than a year now i want to give this a +1 from my side.

in my usecase elements are used instea of percentage-steps as i am tracking the scrolling of a single page site and elements a re just more descriptive - so i would like to send an interaction-event if an element further down is scrolled into the viewport (meaning the visitor is really interacting with my site)

i would say both - for percentages and elements - it would be desirable that one can specify a point / element after which the event counts as an interaction and thus the visit does not count as a bounce anymore.

i would suggest a simple option like:

```javascript
jQuery.scrollDepth({
'interactionAfter': '#element'
});
```
for element use

OR
```javascript
jQuery.scrollDepth({
'interactionAfter': 25
});
```
for percentage use

**Comment by erikberger** [comment]
Great plugin! I wanted to see if there was an update here? Would love to be able to specify that reaching a certain percentage or element meant that the user did not bounce even if thats the only page they visited.

**Comment by robflaherty** [comment]
@erikberger thanks :) It's not possible right now to do it using the percentages but you can do it if you turn off the percentage events and just use a custom element.

Using the options in this example, Scroll Depth would only fire events when #div1 and #div2 are reached, and those events would trigger a non-bounce.

```
jQuery.scrollDepth({
  elements: ['#div1', '#div2'],
  percentage: false,
  userTiming: false,
  pixelDepth: false,
  nonInteraction: false
});
```
