### ISSUE TITLE
Allow setting in options for when element tracking event is fired

### ISSUE THREAD

**Issue by lukeruth** [robflaherty/jquery-scrolldepth#83]
Right now it appears to be fired when the top of the element becomes visible in the viewport. It'd be really helpful if you could specify in the options to fire when the entire element is visible, or 25%, 50%, etc is visible.

It seems more in line with the actual behavior you're trying to track since on a marketing section just scrolling over the threshold may not mean they actual viewed/interacted with that element.

Does that make sense?

**Comment by robflaherty** [comment]
Yeah it makes sense. This question has come up a few times :)

Basically I'm not opposed to it but am hesitant because it adds more complexity to the API and it requires changing the event data structure since we'll need to keep track of percentages per element.

When I want to measure if someone has reached the end of a section I just set the tracking element for the beginning of the next section. You can also inject elements into the page at spots you want to measure and then just track those. But yeah it's a bit of a hack, not as elegant as it could be.

**Comment by lukeruth** [comment]
Yea I thought about doing it that way but it feels odd to add markup just for tracking purposes. It also seems confusing to use the ID of the next section in the case where the IDs are also used for anchor links. I guess you're choosing whether to put the cognitive load in code or in the analytics UI.

If your concern is complexity of the API you could start with two options: `.top` how it is now, and use `.top` + the element's outerHeight to trigger it when the element is fully visible. My gut says the second use case is more common when identifying sections but maybe that's just me.
